### ISSUE TITLE
[Suggestion/Question] Disable built-in decrees?

### ISSUE THREAD

**Issue by ProspectPyxis** [ejektaflex/Bountiful#131]
Is there some option to completely remove all of the built-in decrees in order to replace them with my own custom ones? If not, I'd love this to be properly added as a feature, if possible.

I've tried replacing the decrees with a blank json file, but the decrees still load, they just don't give any actual bounties.

**Comment by CKY-** [comment]
This would be great to have. Having all the json files in the config folder so that other mods can be added by pack makers. or if someone removes quark crates so that thermal creates take over or simple farming creates.Adding quark simple farming and thermal to a pack  you end up with 3 of the same type of crate. Using KubeJS to remove all the irrelevant ones works but then bounties can't be turned in because they have been disabled in JEI. 



To expand on the idea here:  move all the json files to the config and allow for others to be created. on update if you add any more  check if they are missing and add them?

**Comment by ejektaflex** [comment]
If we use a config only system, then we lose the power that datapacks provide. However, I do understand this limitation and I'd like to circumvent it as well. I'm mostly working on the Fabric version, but there I've implemented it so that it uses both config and datapack data, allowing configs to overwrite datapacks.

I'll try add a "disabled" key for Decrees when I have some time, so you can overwrite the decree file and an empty one with a single "disabled": true key :)

As for mod compat, those problems are just as commonplace with configs as datapacks. If somebody removes a mod, you have to edit a config just like you have to edit the datapack. But, I'd still like to avoid creating a blank file as well, so we'll see.

**Comment by Darkmega18** [comment]
yes. would appreciate. I'm seeing this as a potential issue also, because I don't really want all this decree stuff locked in as much as it seems to be. I'd just want to make a list of potential things straight up then have currency or very specific item based rewards like I could do in 1.12.2. :V

would one be able to somewhat achieve this by making all the decrees pull from the same rewards and offers simultaneously which contain that which is desired?

**Comment by Maxwelllondon92** [comment]
I also try to disable them and found two ways.
First is to open the mod jar file with winrar and delete the decrees entirely. This should be done with every update and works globally across saves.

Second is to place in the datapack decrees folder a blank copy of each of them.
I tried to write in each copy {"spawnsInBoard": false}, but they still show up, just as blank bounties with no objectives and no rewards.

So, @ejektaflex. Would be possible to just enable the "spawnsInBoard": false in built-in decrees?

**Comment by ejektaflex** [comment]
I'll take a look at that. In 1.12 I used a config option that let people specify paths that they wanted to DISABLE the loading of. You could add a line that is `"pools/quark/*"` and it would disable all quark pools. Thus, defining `"*/*"` would disable all built in bounty decrees and pools.

I can look into re-adding this functionality. It never carried over into the new config format, partially because the format is different and partially because I felt like nobody used this feature :^)

**Comment by Darkmega18** [comment]
> because I felt like nobody used this feature :^)

surprise!

**Comment by Th3WhiteWolf** [comment]
is there anyway to add new decrees from another mods and create bounties based on these if not, is there anyway to add new bounties and rewards using the actual decrees?

**Comment by ejektaflex** [comment]
@Th3WhiteWolf Yes, using data packs.

**Comment by ejektaflex** [comment]
In 1.19.4+, you can disable builtin decrees by adding a load exception for "*/bounty_decrees/*" in the config. You can also much more easily overwrite or create new decrees *without* a datapack, by doing what you'd do with a datapack but just throwing it in the config folders.
